# Everything under this section should not be touch by end user, generate it using command from web app
# (aside from cert path if necessary)
ConsoleConfiguration:
  ID: ""
  Host: "0.0.0.0"
  Port: 0
  SSL:
    Enabled: false
    CertPath: "/cert/cert.pem"
    KeyPath: "/cert/key.pem"
  Remote: ""
  Secret: ""
# Plugin messages
Messages:
  UnknownSubcommand: "&4Sorry, that command doesn't exist !"
  OnlyConsole: "&4Sorry, but this command can only be executed via console !" #TODO: edit
  OnlyOP: "&4Sorry, but this command can only be executed if you are operator !"
  WrongUsage: "&4That is wrong usage !"
  SuccessSetup: "&2Setup was successful, restarting your server in 3 seconds... !"
  SuccessStop: "&2Tabby webserver successfully stopped !"