# Everything under this section should not be touch by end user, generate it using command from web app
ConsoleConfiguration:
  ID: ""
  Host: "0.0.0.0"
  Port: 0
  Remote: ""
  Secret: ""
# Plugin messages
Messages:
  OnlyConsole: "&4Sorry, but this command can only be executed via console !" #TODO: edit
  WrongUsage: "&4That is wrong usage !"
  SuccessSetup: "&2Setup was successful, restart your server now !"