name: Publish plugin release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 8
          distribution: temurin
          cache: maven

      - name: Download and run BuildTools
        run: |
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 1.12.2

      - name: Change version
        id: version
        env:
          REF: ${{ github.ref }}
        run: sed -i "s/canary/${REF:11}/g" pom.xml

      - name: Build plugin
        run: mvn -B package --file pom.xml

      - name: Generate SHA checksum
        run: |
          cd target/
          CHECKSUM=`sha256sum TeddyControl.jar`
          cd ..
          echo $CHECKSUM > checksum.txt
          echo -e "### SHA256 Checksum\n\`\`\`\n$CHECKSUM\n\`\`\`" >> checksum_md.txt

      - name: Create release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            target/TeddyControl.jar
            checksum.txt
          draft: true
          generate_release_notes: true
          append_body: true
          body_path: checksum_md.txt